// This file is auto-generated by @hey-api/openapi-ts

export type ActivitiesPublic = {
    data: Array<ActivityPublic>;
    count: number;
};

export type ActivityCardio = {
    distance_meters?: number;
    avg_pace_seconds_per_km?: (number | null);
    avg_hr?: (number | null);
    max_hr?: (number | null);
    elevation_gain_meters?: number;
    calories?: (number | null);
    cadence_avg?: (number | null);
    map_summary_polyline?: (string | null);
    splits?: Array<{
        [key: string]: unknown;
    }>;
    heart_rate_zones?: Array<{
        [key: string]: unknown;
    }>;
    rpe?: (number | null);
    perceived_effort_notes?: (string | null);
    shoe_id?: (string | null);
    gear_id?: (string | null);
    id?: string;
    activity_id: string;
};

export type ActivityCardioBase = {
    distance_meters?: number;
    avg_pace_seconds_per_km?: (number | null);
    avg_hr?: (number | null);
    max_hr?: (number | null);
    elevation_gain_meters?: number;
    calories?: (number | null);
    cadence_avg?: (number | null);
    map_summary_polyline?: (string | null);
    splits?: Array<{
        [key: string]: unknown;
    }>;
    heart_rate_zones?: Array<{
        [key: string]: unknown;
    }>;
    rpe?: (number | null);
    perceived_effort_notes?: (string | null);
    shoe_id?: (string | null);
    gear_id?: (string | null);
};

export type ActivityCreate = {
    source_id: string;
    source_type: string;
    timestamp: string;
    duration_seconds?: number;
    name?: (string | null);
    sport_type?: (string | null);
    cardio?: (ActivityCardioBase | null);
};

export type ActivityPublic = {
    source_id: string;
    source_type: string;
    timestamp: string;
    duration_seconds?: number;
    name?: (string | null);
    sport_type?: (string | null);
    id: string;
    user_id: string;
    created_at: string;
    cardio?: (ActivityCardioBase | null);
};

export type ActivityShoeAssignment = {
    shoe_id?: (string | null);
};

export type ActivitySummaryCalendarDay = {
    date: string;
    types: Array<(string)>;
};

export type ActivitySummaryMonthly = {
    total_activities: number;
    target_activities?: (number | null);
    target_source?: (string | null);
    progress?: (number | null);
};

export type ActivitySummaryPublic = {
    month: string;
    period_start: string;
    period_end: string;
    total_activities: number;
    coverage: number;
    by_type: Array<ActivityTypeSummary>;
    monthly: ActivitySummaryMonthly;
    calendar: Array<ActivitySummaryCalendarDay>;
};

export type ActivityTypeSummary = {
    type: string;
    category: string;
    count: number;
    distance_meters: number;
    duration_seconds: number;
    elevation_gain_meters: number;
    avg_distance_meters: number;
    avg_duration_seconds: number;
    avg_elevation_gain_meters: number;
    dot_days: Array<(string)>;
};

export type ActivityUpdate = {
    timestamp?: (string | null);
    duration_seconds?: (number | null);
    name?: (string | null);
};

export type Body_activities_upload_activity_file = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_storage_upload_file = {
    file: string;
};

export type CardioAnalyticsPublic = {
    from_date: (string | null);
    to_date: (string | null);
    distance_meters: number;
    duration_seconds: number;
    average_pace_seconds_per_km: (number | null);
    sessions: number;
};

export type ConnectionStatus = {
    provider: string;
    connected: boolean;
    expires_at?: (string | null);
};

export type DashboardActivity = {
    id: string;
    timestamp: string;
    name: (string | null);
    source_type: string;
    duration_seconds: number;
    distance_meters?: (number | null);
};

export type DashboardDay = {
    date: string;
    activities: Array<DashboardActivity>;
};

export type DashboardKPIs = {
    cardio_distance_meters: number;
    cardio_duration_seconds: number;
    cardio_avg_pace_seconds_per_km: (number | null);
    sessions: number;
    active_days: number;
};

export type DashboardPublic = {
    week_start: string;
    week_end: string;
    kpis: DashboardKPIs;
    timeline: Array<DashboardDay>;
    upcoming_race?: (UpcomingRacePublic | null);
    previous_kpis?: (DashboardKPIs | null);
    sync_state?: Array<SyncStateEntry>;
};

export type HrTrendPoint = {
    week: string;
    avg_hr?: (number | null);
    max_hr?: (number | null);
};

export type HrTrendPublic = {
    data?: Array<HrTrendPoint>;
};

export type HrZonesPublic = {
    weeks?: Array<{
        [key: string]: unknown;
    }>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IntegrationStatus = {
    provider: string;
    connected: boolean;
    message?: (string | null);
};

export type IntegrationTestResult = {
    provider: string;
    success: boolean;
    message: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PhaseIn = {
    position?: number;
    name: string;
    color?: string;
    start_week: number;
    end_week: number;
    objective?: (string | null);
    description?: (string | null);
    weeks?: Array<WeekIn>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RaceCreate = {
    event_name: string;
    date: string;
    location?: (string | null);
    distance_km: number;
    priority?: 'A' | 'B' | 'C';
    target_time_seconds?: (number | null);
    target_pace_seconds_per_km?: (number | null);
    official_time_seconds?: (number | null);
    official_pace_seconds_per_km?: (number | null);
    chip_time_seconds?: (number | null);
    position?: (number | null);
    category?: (string | null);
    bib_number?: (string | null);
    photos_urls?: Array<(string)>;
    notes?: (string | null);
    shoe_id?: (string | null);
    activity_id?: (string | null);
};

export type priority = 'A' | 'B' | 'C';

export type RacePublic = {
    event_name: string;
    date: string;
    location?: (string | null);
    distance_km: number;
    priority?: 'A' | 'B' | 'C';
    target_time_seconds?: (number | null);
    target_pace_seconds_per_km?: (number | null);
    official_time_seconds?: (number | null);
    official_pace_seconds_per_km?: (number | null);
    chip_time_seconds?: (number | null);
    position?: (number | null);
    category?: (string | null);
    bib_number?: (string | null);
    photos_urls?: Array<(string)>;
    notes?: (string | null);
    shoe_id?: (string | null);
    id: string;
    activity_id: (string | null);
    user_id: string;
    created_at: string;
};

export type RacesPublic = {
    data: Array<RacePublic>;
    count: number;
};

export type RaceUpdate = {
    event_name?: (string | null);
    date?: (string | null);
    location?: (string | null);
    distance_km?: (number | null);
    priority?: ('A' | 'B' | 'C' | null);
    target_time_seconds?: (number | null);
    target_pace_seconds_per_km?: (number | null);
    official_time_seconds?: (number | null);
    official_pace_seconds_per_km?: (number | null);
    chip_time_seconds?: (number | null);
    position?: (number | null);
    category?: (string | null);
    bib_number?: (string | null);
    photos_urls?: (Array<(string)> | null);
    notes?: (string | null);
    activity_id?: (string | null);
    shoe_id?: (string | null);
};

export type RunningPhasePublic = {
    id: string;
    position: number;
    name: string;
    color: string;
    start_week: number;
    end_week: number;
    objective: (string | null);
    description: (string | null);
    weeks?: Array<RunningWeekPublic>;
};

export type RunningPlanCreate = {
    name: string;
    goal?: (string | null);
    distance_km?: (number | null);
    distance_unit?: 'km' | 'mi';
    target_time_seconds?: (number | null);
    target_pace_seconds_per_km?: (number | null);
    start_date: string;
    end_date?: (string | null);
    notes?: (string | null);
    status?: 'planned' | 'active' | 'completed';
    race_id?: (string | null);
    phases?: Array<PhaseIn>;
};

export type distance_unit = 'km' | 'mi';

export type status = 'planned' | 'active' | 'completed';

export type RunningPlanPublic = {
    id: string;
    user_id: string;
    race_id: (string | null);
    name: string;
    goal: (string | null);
    distance_km: (number | null);
    distance_unit: string;
    target_time_seconds: (number | null);
    target_pace_seconds_per_km: (number | null);
    start_date: string;
    end_date: (string | null);
    status: 'planned' | 'active' | 'completed';
    notes: (string | null);
    created_at: string;
    updated_at: string;
    phases?: Array<RunningPhasePublic>;
};

export type RunningPlansPublic = {
    data: Array<RunningPlanSummaryPublic>;
    count: number;
};

export type RunningPlanSummaryPublic = {
    id: string;
    name: string;
    goal: (string | null);
    status: 'planned' | 'active' | 'completed';
    start_date: string;
    end_date: (string | null);
    distance_km: (number | null);
    distance_unit: string;
    race_id: (string | null);
    updated_at: string;
    weeks: number;
    sessions: number;
    planned_km: number;
    completed: number;
    missed: number;
    planned: number;
};

/**
 * Reemplazo completo del plan: usa los mismos campos que la creación.
 */
export type RunningPlanUpdate = {
    name: string;
    goal?: (string | null);
    distance_km?: (number | null);
    distance_unit?: 'km' | 'mi';
    target_time_seconds?: (number | null);
    target_pace_seconds_per_km?: (number | null);
    start_date: string;
    end_date?: (string | null);
    notes?: (string | null);
    status?: 'planned' | 'active' | 'completed';
    race_id?: (string | null);
    phases?: Array<PhaseIn>;
};

export type RunningWeekPublic = {
    id: string;
    number: number;
    start_date: (string | null);
    end_date: (string | null);
    name: (string | null);
    objective: (string | null);
    notes: (string | null);
    workouts?: Array<RunningWorkoutPublic>;
};

export type RunningWorkoutPublic = {
    id: string;
    date: string;
    type: 'easy_run' | 'regeneration' | 'intervals' | 'tempo' | 'long_run' | 'test' | 'activation' | 'race';
    objective: (string | null);
    name: (string | null);
    distance_km: (number | null);
    duration_seconds: (number | null);
    pace_seconds_per_km: (number | null);
    intensity: 'easy' | 'moderate' | 'hard';
    description: (string | null);
    notes: (string | null);
    cancelled: boolean;
    status_override?: ('completed' | 'missed' | null);
    status: 'planned' | 'completed' | 'missed' | 'cancelled';
    matched_activity: ({
    [key: string]: unknown;
} | null);
    blocks?: Array<WorkoutBlockPublic>;
};

export type type = 'easy_run' | 'regeneration' | 'intervals' | 'tempo' | 'long_run' | 'test' | 'activation' | 'race';

export type intensity = 'easy' | 'moderate' | 'hard';

export type status2 = 'planned' | 'completed' | 'missed' | 'cancelled';

/**
 * Campos editables de una sesión (PATCH parcial).
 */
export type RunningWorkoutUpdate = {
    cancelled?: (boolean | null);
    status_override?: ('completed' | 'missed' | null);
    date?: (string | null);
    type?: ('easy_run' | 'regeneration' | 'intervals' | 'tempo' | 'long_run' | 'test' | 'activation' | 'race' | null);
    objective?: (string | null);
    name?: (string | null);
    distance_km?: (number | null);
    duration_seconds?: (number | null);
    pace_seconds_per_km?: (number | null);
    intensity?: ('easy' | 'moderate' | 'hard' | null);
    description?: (string | null);
    notes?: (string | null);
};

export type SettingsPublic = {
    connections: Array<ConnectionStatus>;
    goals?: (WeeklyGoalPublic | null);
};

export type ShoeActivitiesPublic = {
    data: Array<ActivityPublic>;
    count: number;
};

export type ShoeCreate = {
    name: string;
    brand?: (string | null);
    model?: (string | null);
    category: 'training' | 'race' | 'trail' | 'easy' | 'mixed';
    purchase_date?: (string | null);
    target_distance_km?: (number | null);
    color?: (string | null);
    photo_url?: (string | null);
    notes?: (string | null);
    is_active?: boolean;
};

export type category = 'training' | 'race' | 'trail' | 'easy' | 'mixed';

export type ShoeImportResult = {
    imported?: number;
    updated?: number;
    linked?: number;
    assigned?: number;
    message?: string;
};

export type ShoePublic = {
    name: string;
    brand?: (string | null);
    model?: (string | null);
    category: 'training' | 'race' | 'trail' | 'easy' | 'mixed';
    purchase_date?: (string | null);
    target_distance_km?: (number | null);
    color?: (string | null);
    photo_url?: (string | null);
    notes?: (string | null);
    is_active?: boolean;
    id: string;
    user_id: string;
    strava_gear_id?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ShoesPublic = {
    data: Array<ShoePublic>;
    count: number;
};

export type ShoeStatsPublic = {
    total_distance_meters?: number;
    sessions?: number;
    avg_pace_seconds_per_km?: (number | null);
    avg_hr?: (number | null);
    target_distance_km?: (number | null);
    races?: Array<RacePublic>;
};

export type ShoeUpdate = {
    name?: (string | null);
    brand?: (string | null);
    model?: (string | null);
    category?: ('training' | 'race' | 'trail' | 'easy' | 'mixed' | null);
    purchase_date?: (string | null);
    target_distance_km?: (number | null);
    color?: (string | null);
    photo_url?: (string | null);
    notes?: (string | null);
    is_active?: (boolean | null);
};

export type StravaCredentialsIn = {
    client_id?: (string | null);
    client_secret?: (string | null);
    access_token?: (string | null);
    refresh_token?: (string | null);
    expires_at?: (string | null);
};

export type SyncLogPublic = {
    provider: string;
    status: string;
    details?: {
        [key: string]: unknown;
    };
    id: string;
    started_at: string;
    completed_at?: (string | null);
    user_id: string;
};

export type SyncLogsPublic = {
    data: Array<SyncLogPublic>;
    count: number;
};

export type SyncSchedulePublic = {
    provider: string;
    enabled?: boolean;
    interval_hours?: number;
    id: string;
    user_id: string;
    last_run_at?: (string | null);
};

export type SyncScheduleUpdate = {
    enabled?: (boolean | null);
    interval_hours?: (number | null);
};

export type SyncStateEntry = {
    provider: string;
    connected: boolean;
    last_status?: (string | null);
    last_message?: (string | null);
    last_run_at?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpcomingRacePublic = {
    id: string;
    event_name: string;
    date: string;
    location: (string | null);
    distance_km: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WeekIn = {
    number: number;
    start_date?: (string | null);
    end_date?: (string | null);
    name?: (string | null);
    objective?: (string | null);
    notes?: (string | null);
    workouts?: Array<WorkoutIn>;
};

export type WeeklyGoalBase = {
    target_km?: (number | null);
    target_sessions?: (number | null);
    target_long_run_km?: (number | null);
};

export type WeeklyGoalPublic = {
    target_km?: (number | null);
    target_sessions?: (number | null);
    target_long_run_km?: (number | null);
    id: string;
    user_id: string;
    created_at: string;
};

export type WorkoutBlockIn = {
    position?: number;
    block_type?: 'warmup' | 'main' | 'interval' | 'recovery' | 'cooldown' | 'strides';
    repeats?: number;
    distance_m?: (number | null);
    duration_seconds?: (number | null);
    pace_seconds_per_km?: (number | null);
    pace_range_end_seconds_per_km?: (number | null);
    recovery_seconds?: (number | null);
    recovery_type?: (string | null);
    notes?: (string | null);
};

export type block_type = 'warmup' | 'main' | 'interval' | 'recovery' | 'cooldown' | 'strides';

export type WorkoutBlockPublic = {
    id: string;
    position: number;
    block_type: 'warmup' | 'main' | 'interval' | 'recovery' | 'cooldown' | 'strides';
    repeats: number;
    distance_m: (number | null);
    duration_seconds: (number | null);
    pace_seconds_per_km: (number | null);
    pace_range_end_seconds_per_km: (number | null);
    recovery_seconds: (number | null);
    recovery_type: (string | null);
    notes: (string | null);
};

/**
 * Body opcional de duplicación: permite elegir la fecha destino.
 */
export type WorkoutDuplicateIn = {
    date?: (string | null);
};

export type WorkoutIn = {
    date: string;
    type: 'easy_run' | 'regeneration' | 'intervals' | 'tempo' | 'long_run' | 'test' | 'activation' | 'race';
    objective?: (string | null);
    name?: (string | null);
    distance_km?: (number | null);
    duration_seconds?: (number | null);
    pace_seconds_per_km?: (number | null);
    intensity?: 'easy' | 'moderate' | 'hard';
    description?: (string | null);
    notes?: (string | null);
    cancelled?: boolean;
    status_override?: ('completed' | 'missed' | null);
    blocks?: Array<WorkoutBlockIn>;
};

export type ActivitiesReadActivitiesData = {
    fromDate?: (string | null);
    limit?: number;
    skip?: number;
    sourceType?: (string | null);
    toDate?: (string | null);
};

export type ActivitiesReadActivitiesResponse = (ActivitiesPublic);

export type ActivitiesCreateActivityData = {
    requestBody: ActivityCreate;
};

export type ActivitiesCreateActivityResponse = (ActivityPublic);

export type ActivitiesReadCardioMetricsData = {
    activityId: string;
};

export type ActivitiesReadCardioMetricsResponse = (ActivityCardio);

export type ActivitiesReadActivityData = {
    activityId: string;
};

export type ActivitiesReadActivityResponse = (ActivityPublic);

export type ActivitiesUpdateActivityData = {
    activityId: string;
    requestBody: ActivityUpdate;
};

export type ActivitiesUpdateActivityResponse = (ActivityPublic);

export type ActivitiesDeleteActivityData = {
    activityId: string;
};

export type ActivitiesDeleteActivityResponse = ({
    [key: string]: (string);
});

export type ActivitiesAssignActivityShoeData = {
    activityId: string;
    requestBody: ActivityShoeAssignment;
};

export type ActivitiesAssignActivityShoeResponse = (ActivityPublic);

export type ActivitiesUploadActivityFileData = {
    formData: Body_activities_upload_activity_file;
};

export type ActivitiesUploadActivityFileResponse = (ActivityPublic);

export type AnalyticsReadCardioAnalyticsData = {
    fromDate?: (string | null);
    toDate?: (string | null);
};

export type AnalyticsReadCardioAnalyticsResponse = (CardioAnalyticsPublic);

export type AnalyticsReadDashboardData = {
    /**
     * Monday that starts the requested week
     */
    weekStart: string;
};

export type AnalyticsReadDashboardResponse = (DashboardPublic);

export type AnalyticsReadCardioMonthlyData = {
    months?: number;
};

export type AnalyticsReadCardioMonthlyResponse = (Array<{
    [key: string]: unknown;
}>);

export type AnalyticsReadCardioBestPacesResponse = (Array<{
    [key: string]: unknown;
}>);

export type AnalyticsReadCardioHrZonesData = {
    weeks?: number;
};

export type AnalyticsReadCardioHrZonesResponse = (HrZonesPublic);

export type AnalyticsReadCardioHrTrendData = {
    weeks?: number;
};

export type AnalyticsReadCardioHrTrendResponse = (HrTrendPublic);

export type AnalyticsReadActivitiesSummaryData = {
    /**
     * Mes en formato YYYY-MM
     */
    month?: (string | null);
};

export type AnalyticsReadActivitiesSummaryResponse = (ActivitySummaryPublic);

export type AuthStartStravaAuthResponse = ({
    [key: string]: (string);
});

export type AuthFinishStravaAuthData = {
    code?: (string | null);
    error?: (string | null);
    scope?: (string | null);
    state?: (string | null);
};

export type AuthFinishStravaAuthResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RacesReadRacesData = {
    distanceKm?: (number | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type RacesReadRacesResponse = (RacesPublic);

export type RacesCreateRaceData = {
    requestBody: RaceCreate;
};

export type RacesCreateRaceResponse = (RacePublic);

export type RacesReadRaceData = {
    raceId: string;
};

export type RacesReadRaceResponse = (RacePublic);

export type RacesUpdateRaceData = {
    raceId: string;
    requestBody: RaceUpdate;
};

export type RacesUpdateRaceResponse = (RacePublic);

export type RacesDeleteRaceData = {
    raceId: string;
};

export type RacesDeleteRaceResponse = ({
    [key: string]: (string);
});

export type RunningPlansReadPlansResponse = (RunningPlansPublic);

export type RunningPlansCreatePlanData = {
    requestBody: RunningPlanCreate;
};

export type RunningPlansCreatePlanResponse = (RunningPlanPublic);

export type RunningPlansReadPlanData = {
    planId: string;
};

export type RunningPlansReadPlanResponse = (RunningPlanPublic);

export type RunningPlansReplacePlanData = {
    planId: string;
    requestBody: RunningPlanUpdate;
};

export type RunningPlansReplacePlanResponse = (RunningPlanPublic);

export type RunningPlansDeletePlanData = {
    planId: string;
};

export type RunningPlansDeletePlanResponse = ({
    [key: string]: (string);
});

export type RunningPlansUpdateWorkoutData = {
    planId: string;
    requestBody: RunningWorkoutUpdate;
    workoutId: string;
};

export type RunningPlansUpdateWorkoutResponse = (RunningWorkoutPublic);

export type RunningPlansDuplicateWorkoutData = {
    planId: string;
    requestBody?: (WorkoutDuplicateIn | null);
    workoutId: string;
};

export type RunningPlansDuplicateWorkoutResponse = (RunningWorkoutPublic);

export type SettingsReadSettingsResponse = (SettingsPublic);

export type SettingsReadGoalsResponse = ((WeeklyGoalPublic | null));

export type SettingsUpdateGoalsData = {
    requestBody: WeeklyGoalBase;
};

export type SettingsUpdateGoalsResponse = (WeeklyGoalPublic);

export type SettingsSaveStravaCredentialsData = {
    requestBody: StravaCredentialsIn;
};

export type SettingsSaveStravaCredentialsResponse = (IntegrationStatus);

export type SettingsReadIntegrationStatusData = {
    provider: string;
};

export type SettingsReadIntegrationStatusResponse = (IntegrationStatus);

export type SettingsDisconnectIntegrationData = {
    provider: string;
};

export type SettingsDisconnectIntegrationResponse = (IntegrationStatus);

export type SettingsTestIntegrationData = {
    provider: string;
};

export type SettingsTestIntegrationResponse = (IntegrationTestResult);

export type SettingsReadSyncScheduleResponse = (Array<SyncSchedulePublic>);

export type SettingsUpdateSyncScheduleData = {
    provider: string;
    requestBody: SyncScheduleUpdate;
};

export type SettingsUpdateSyncScheduleResponse = (SyncSchedulePublic);

export type ShoesReadShoesData = {
    category?: ('training' | 'race' | 'trail' | 'easy' | 'mixed' | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ShoesReadShoesResponse = (ShoesPublic);

export type ShoesCreateShoeData = {
    requestBody: ShoeCreate;
};

export type ShoesCreateShoeResponse = (ShoePublic);

export type ShoesImportStravaShoesResponse = (ShoeImportResult);

export type ShoesReadShoeData = {
    shoeId: string;
};

export type ShoesReadShoeResponse = (ShoePublic);

export type ShoesUpdateShoeData = {
    requestBody: ShoeUpdate;
    shoeId: string;
};

export type ShoesUpdateShoeResponse = (ShoePublic);

export type ShoesDeleteShoeData = {
    shoeId: string;
};

export type ShoesDeleteShoeResponse = ({
    [key: string]: (string);
});

export type ShoesReadShoeStatsData = {
    shoeId: string;
};

export type ShoesReadShoeStatsResponse = (ShoeStatsPublic);

export type ShoesReadShoeActivitiesData = {
    limit?: number;
    shoeId: string;
    skip?: number;
};

export type ShoesReadShoeActivitiesResponse = (ShoeActivitiesPublic);

export type StorageUploadFileData = {
    formData: Body_storage_upload_file;
};

export type StorageUploadFileResponse = ({
    [key: string]: (string);
});

export type StorageReadFileData = {
    filename: string;
};

export type StorageReadFileResponse = (unknown);

export type SyncTriggerSyncData = {
    provider: string;
};

export type SyncTriggerSyncResponse = (SyncLogPublic);

export type SyncReadSyncLogsData = {
    limit?: number;
};

export type SyncReadSyncLogsResponse = (SyncLogsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WebhooksVerifyStravaWebhookData = {
    hubChallenge: string;
    hubMode: string;
    hubVerifyToken: string;
};

export type WebhooksVerifyStravaWebhookResponse = ({
    [key: string]: (string);
});

export type WebhooksReceiveStravaWebhookData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type WebhooksReceiveStravaWebhookResponse = ({
    [key: string]: (string);
});