/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutToolsRouteImport } from './routes/_layout/tools'
import { Route as LayoutActivitiesIndexRouteImport } from './routes/_layout/activities/index'
import { Route as LayoutActivitiesActivityIdRouteImport } from './routes/_layout/activities/$activityId'
import { Route as LayoutAnalyticsIndexRouteImport } from './routes/_layout/analytics/index'
import { Route as LayoutAnalyticsCardioRouteImport } from './routes/_layout/analytics/cardio'
import { Route as LayoutAnalyticsStrengthRouteImport } from './routes/_layout/analytics/strength'
import { Route as LayoutRacesIndexRouteImport } from './routes/_layout/races/index'
import { Route as LayoutRacesRaceIdRouteImport } from './routes/_layout/races/$raceId'
import { Route as LayoutRoutinesIndexRouteImport } from './routes/_layout/routines/index'
import { Route as LayoutRoutinesRoutineIdRouteImport } from './routes/_layout/routines/$routineId'
import { Route as LayoutShoesIndexRouteImport } from './routes/_layout/shoes/index'
import { Route as LayoutShoesShoeIdRouteImport } from './routes/_layout/shoes/$shoeId'
import { Route as LayoutRoutinesRunPlanIdRouteImport } from './routes/_layout/routines/run/$planId'
import { Route as LayoutRoutinesRunNewRouteImport } from './routes/_layout/routines/run/new'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesIndexRoute = LayoutActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesActivityIdRoute =
  LayoutActivitiesActivityIdRouteImport.update({
    id: '/activities/$activityId',
    path: '/activities/$activityId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAnalyticsIndexRoute = LayoutAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsCardioRoute = LayoutAnalyticsCardioRouteImport.update({
  id: '/analytics/cardio',
  path: '/analytics/cardio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsStrengthRoute = LayoutAnalyticsStrengthRouteImport.update({
  id: '/analytics/strength',
  path: '/analytics/strength',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRacesIndexRoute = LayoutRacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRacesRaceIdRoute = LayoutRacesRaceIdRouteImport.update({
  id: '/races/$raceId',
  path: '/races/$raceId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoutinesIndexRoute = LayoutRoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoutinesRoutineIdRoute = LayoutRoutinesRoutineIdRouteImport.update({
  id: '/routines/$routineId',
  path: '/routines/$routineId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShoesIndexRoute = LayoutShoesIndexRouteImport.update({
  id: '/shoes/',
  path: '/shoes/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShoesShoeIdRoute = LayoutShoesShoeIdRouteImport.update({
  id: '/shoes/$shoeId',
  path: '/shoes/$shoeId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoutinesRunPlanIdRoute = LayoutRoutinesRunPlanIdRouteImport.update({
  id: '/routines/run/$planId',
  path: '/routines/run/$planId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoutinesRunNewRoute = LayoutRoutinesRunNewRouteImport.update({
  id: '/routines/run/new',
  path: '/routines/run/new',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof LayoutSettingsRoute
  '/tools': typeof LayoutToolsRoute
  '/activities/$activityId': typeof LayoutActivitiesActivityIdRoute
  '/analytics/cardio': typeof LayoutAnalyticsCardioRoute
  '/analytics/strength': typeof LayoutAnalyticsStrengthRoute
  '/races/$raceId': typeof LayoutRacesRaceIdRoute
  '/routines/$routineId': typeof LayoutRoutinesRoutineIdRoute
  '/shoes/$shoeId': typeof LayoutShoesShoeIdRoute
  '/activities/': typeof LayoutActivitiesIndexRoute
  '/analytics/': typeof LayoutAnalyticsIndexRoute
  '/races/': typeof LayoutRacesIndexRoute
  '/routines/': typeof LayoutRoutinesIndexRoute
  '/shoes/': typeof LayoutShoesIndexRoute
  '/routines/run/$planId': typeof LayoutRoutinesRunPlanIdRoute
  '/routines/run/new': typeof LayoutRoutinesRunNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof LayoutSettingsRoute
  '/tools': typeof LayoutToolsRoute
  '/': typeof LayoutIndexRoute
  '/activities/$activityId': typeof LayoutActivitiesActivityIdRoute
  '/analytics/cardio': typeof LayoutAnalyticsCardioRoute
  '/analytics/strength': typeof LayoutAnalyticsStrengthRoute
  '/races/$raceId': typeof LayoutRacesRaceIdRoute
  '/routines/$routineId': typeof LayoutRoutinesRoutineIdRoute
  '/shoes/$shoeId': typeof LayoutShoesShoeIdRoute
  '/activities': typeof LayoutActivitiesIndexRoute
  '/analytics': typeof LayoutAnalyticsIndexRoute
  '/races': typeof LayoutRacesIndexRoute
  '/routines': typeof LayoutRoutinesIndexRoute
  '/shoes': typeof LayoutShoesIndexRoute
  '/routines/run/$planId': typeof LayoutRoutinesRunPlanIdRoute
  '/routines/run/new': typeof LayoutRoutinesRunNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tools': typeof LayoutToolsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/activities/$activityId': typeof LayoutActivitiesActivityIdRoute
  '/_layout/analytics/cardio': typeof LayoutAnalyticsCardioRoute
  '/_layout/analytics/strength': typeof LayoutAnalyticsStrengthRoute
  '/_layout/races/$raceId': typeof LayoutRacesRaceIdRoute
  '/_layout/routines/$routineId': typeof LayoutRoutinesRoutineIdRoute
  '/_layout/shoes/$shoeId': typeof LayoutShoesShoeIdRoute
  '/_layout/activities/': typeof LayoutActivitiesIndexRoute
  '/_layout/analytics/': typeof LayoutAnalyticsIndexRoute
  '/_layout/races/': typeof LayoutRacesIndexRoute
  '/_layout/routines/': typeof LayoutRoutinesIndexRoute
  '/_layout/shoes/': typeof LayoutShoesIndexRoute
  '/_layout/routines/run/$planId': typeof LayoutRoutinesRunPlanIdRoute
  '/_layout/routines/run/new': typeof LayoutRoutinesRunNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/settings'
    | '/tools'
    | '/activities/$activityId'
    | '/analytics/cardio'
    | '/analytics/strength'
    | '/races/$raceId'
    | '/routines/$routineId'
    | '/shoes/$shoeId'
    | '/activities/'
    | '/analytics/'
    | '/races/'
    | '/routines/'
    | '/shoes/'
    | '/routines/run/$planId'
    | '/routines/run/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/settings'
    | '/tools'
    | '/'
    | '/activities/$activityId'
    | '/analytics/cardio'
    | '/analytics/strength'
    | '/races/$raceId'
    | '/routines/$routineId'
    | '/shoes/$shoeId'
    | '/activities'
    | '/analytics'
    | '/races'
    | '/routines'
    | '/shoes'
    | '/routines/run/$planId'
    | '/routines/run/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/settings'
    | '/_layout/tools'
    | '/_layout/'
    | '/_layout/activities/$activityId'
    | '/_layout/analytics/cardio'
    | '/_layout/analytics/strength'
    | '/_layout/races/$raceId'
    | '/_layout/routines/$routineId'
    | '/_layout/shoes/$shoeId'
    | '/_layout/activities/'
    | '/_layout/analytics/'
    | '/_layout/races/'
    | '/_layout/routines/'
    | '/_layout/shoes/'
    | '/_layout/routines/run/$planId'
    | '/_layout/routines/run/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities/': {
      id: '/_layout/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof LayoutActivitiesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities/$activityId': {
      id: '/_layout/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof LayoutActivitiesActivityIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/': {
      id: '/_layout/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof LayoutAnalyticsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/cardio': {
      id: '/_layout/analytics/cardio'
      path: '/analytics/cardio'
      fullPath: '/analytics/cardio'
      preLoaderRoute: typeof LayoutAnalyticsCardioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/strength': {
      id: '/_layout/analytics/strength'
      path: '/analytics/strength'
      fullPath: '/analytics/strength'
      preLoaderRoute: typeof LayoutAnalyticsStrengthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/races/': {
      id: '/_layout/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof LayoutRacesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/races/$raceId': {
      id: '/_layout/races/$raceId'
      path: '/races/$raceId'
      fullPath: '/races/$raceId'
      preLoaderRoute: typeof LayoutRacesRaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/routines/': {
      id: '/_layout/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof LayoutRoutinesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/routines/$routineId': {
      id: '/_layout/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof LayoutRoutinesRoutineIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shoes/': {
      id: '/_layout/shoes/'
      path: '/shoes'
      fullPath: '/shoes/'
      preLoaderRoute: typeof LayoutShoesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shoes/$shoeId': {
      id: '/_layout/shoes/$shoeId'
      path: '/shoes/$shoeId'
      fullPath: '/shoes/$shoeId'
      preLoaderRoute: typeof LayoutShoesShoeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/routines/run/$planId': {
      id: '/_layout/routines/run/$planId'
      path: '/routines/run/$planId'
      fullPath: '/routines/run/$planId'
      preLoaderRoute: typeof LayoutRoutinesRunPlanIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/routines/run/new': {
      id: '/_layout/routines/run/new'
      path: '/routines/run/new'
      fullPath: '/routines/run/new'
      preLoaderRoute: typeof LayoutRoutinesRunNewRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutToolsRoute: typeof LayoutToolsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutActivitiesActivityIdRoute: typeof LayoutActivitiesActivityIdRoute
  LayoutAnalyticsCardioRoute: typeof LayoutAnalyticsCardioRoute
  LayoutAnalyticsStrengthRoute: typeof LayoutAnalyticsStrengthRoute
  LayoutRacesRaceIdRoute: typeof LayoutRacesRaceIdRoute
  LayoutRoutinesRoutineIdRoute: typeof LayoutRoutinesRoutineIdRoute
  LayoutShoesShoeIdRoute: typeof LayoutShoesShoeIdRoute
  LayoutActivitiesIndexRoute: typeof LayoutActivitiesIndexRoute
  LayoutAnalyticsIndexRoute: typeof LayoutAnalyticsIndexRoute
  LayoutRacesIndexRoute: typeof LayoutRacesIndexRoute
  LayoutRoutinesIndexRoute: typeof LayoutRoutinesIndexRoute
  LayoutShoesIndexRoute: typeof LayoutShoesIndexRoute
  LayoutRoutinesRunPlanIdRoute: typeof LayoutRoutinesRunPlanIdRoute
  LayoutRoutinesRunNewRoute: typeof LayoutRoutinesRunNewRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutToolsRoute: LayoutToolsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutActivitiesActivityIdRoute: LayoutActivitiesActivityIdRoute,
  LayoutAnalyticsCardioRoute: LayoutAnalyticsCardioRoute,
  LayoutAnalyticsStrengthRoute: LayoutAnalyticsStrengthRoute,
  LayoutRacesRaceIdRoute: LayoutRacesRaceIdRoute,
  LayoutRoutinesRoutineIdRoute: LayoutRoutinesRoutineIdRoute,
  LayoutShoesShoeIdRoute: LayoutShoesShoeIdRoute,
  LayoutActivitiesIndexRoute: LayoutActivitiesIndexRoute,
  LayoutAnalyticsIndexRoute: LayoutAnalyticsIndexRoute,
  LayoutRacesIndexRoute: LayoutRacesIndexRoute,
  LayoutRoutinesIndexRoute: LayoutRoutinesIndexRoute,
  LayoutShoesIndexRoute: LayoutShoesIndexRoute,
  LayoutRoutinesRunPlanIdRoute: LayoutRoutinesRunPlanIdRoute,
  LayoutRoutinesRunNewRoute: LayoutRoutinesRunNewRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
